export const BillingPageLocators2 = {
    OpenPaymentMethod: '//*[@id="app"]/div/div[2]/div/div/div[2]/div[1]/div/div[2]/div/div[1]/div[2]/div/div[2]/div[1]/div[2]/button',
    SelectPaymentMethodCreditCard: '//*[@id="app"]/div/div[2]/div/div/div[2]/div[1]/div/div[2]/div/div/div[2]/div/div[2]/div[1]/div[2]/div/ul/li[1]',
    OpenBillingAddressList: '//*[@id="app"]/div/div[2]/div/div/div[2]/div[1]/div/div[2]/div/div[1]/div[2]/div/div[1]/div[1]/div[2]/div/p/button',
    SelectPaymentAddress: '/html/body/div[3]/div/div/div/div[2]/div/div/div[1]/table/tbody/tr[1]/td[3]/button',
    AcceptPaymentPreference: '//*[@id="headlessui-dialog-8"]/div[2]/div/div/div[2]/button[3]',
    OpemSupplierPocketNurseMethod: '//*[@id="app"]/div/div[2]/div/div/div[2]/div[1]/div/div[2]/div/div[2]/div[2]/div/div[2]/div[1]/div[2]/button',
    SelectPocketNursePaymentMethod: '//*[@id="app"]/div/div[2]/div/div/div[2]/div[1]/div/div[2]/div/div[2]/div[2]/div/div[2]/div[1]/div[2]/div/ul/li/span',
    ReviewOrderButton: '//*[@id="order-summary"]/div[2]/a',
    PlaceOrderButton: '//*[@id="order-summary"]/div[2]/button',
    GoBackToCart: '//*[@id="app"]/div/div[2]/div/div/div[1]/ul/li',
    PullBackPaymentButton: '//*[@id="order-summary"]/div[2]/button',
    PullBackPaymentMethodConfirm: '//*[@id="app"]/div/div[2]/div/div/div/div/div[2]/div[1]/div/div[2]/div[2]/div/div[2]/button',
    targetXPath: '//*[@id="app"]/div/div[4]/div/div[2]/div/div/div/strong',
    targetSuccessXPath: '//*[@id="app"]/div/div[2]/div/div/div/div/div[3]/div[1]/div/div/div[2]/div/div/div[1]/div/h2',
};
